spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    password: a123520
    pool:
      jedis:
        max-idle: 10
        max-active: 100
        max-wait: 100

mybatis:
  type-aliases-package:  com.github.lihang941.example.entity
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.github.lihang941.common.mapper.BaseMapper
  enable-method-annotation: true

pagehelper:
  supportMethodsArguments: true
  params: count=countSql

vertx:
  web:
    webSocketEnable: true
    port: 8088

